---@type vim.lsp.Config
return {
  mason = false,
  cmd = { vim.fn.expand('~/.asdf/shims/ruby-lsp') },
  filetypes = { 'ruby', 'eruby' },
  root_markers = { 'Gemfile', '.git' },
  init_options = {
    bundleGemfile = vim.fn.expand('~/.ruby-lsp/Gemfile'),
    enabledFeatures = {
      'codeActions',
      'completion',
      'definition',
      'diagnostics',
      'documentHighlights',
      'documentLink',
      'documentSymbols',
      'foldingRanges',
      'formatting',
      'hover',
      'selectionRanges',
      'semanticHighlighting',
      'signatureHelp',
      'typeHierarchy',
      'workspaceSymbol',
    },
    experimentalFeaturesEnabled = false,
    formatter = 'auto',
    indexing = {
      excludedPatterns = {
        '**/test/**/*',
        '**/spec/**/*',
        '**/db/**/*',
        '**/vendor/**/*',
        '**/.git',
        '**/.svn',
        '**/.hg',
        '**/CVS',
        '**/.DS_Store',
        '**/tmp/**/*',
        '**/node_modules/**/*',
        '**/bower_components/**/*',
        '**/dist/**/*',
        '**/.git/objects/**',
        '**/.git/subtree-cache/**',
      },
    },
  },
}
