# frozen_string_literal: true

source 'https://rubygems.org'

ruby file: '.tool-versions'

gem 'rubocop'
gem 'rubocop-packaging'
gem 'rubocop-performance'
gem 'rubocop-rails'
gem 'rubocop-rspec'
gem 'rubocop-shopify'
gem 'rubocop-thread_safety'
gem 'ruby-lsp'
gem 'test-prof'
