# Raycast script commands
[".config/vicinae/scripts-commands/epoch-to-human-date.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/epoch-to-human-date.sh"
refreshPeriod = "168h"
[".config/vicinae/scripts-commands/human-date-to-epoch.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/human-date-to-epoch.sh"
refreshPeriod = "168h"
[".config/vicinae/scripts-commands/hex-to-rgb.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/hex-to-rgb.sh"
refreshPeriod = "168h"
[".config/vicinae/scripts-commands/hex-to-rgba.sh"]
type = "file"
url = "https://raw.githubusercontent.com/raycast/script-commands/master/commands/conversions/hex-to-rgba.sh"
refreshPeriod = "168h"
