local M = {
  misc = {
    dots = '󰇘',
  },
  dap = {
    Stopped = { '󰁕 ', 'DiagnosticWarn', 'DapStoppedLine' },
    Breakpoint = ' ',
    BreakpointCondition = ' ',
    BreakpointRejected = { ' ', 'DiagnosticError' },
    LogPoint = '.>',
  },
  diagnostics = {
    Error = ' ',
    Warn = ' ',
    Hint = ' ',
    Info = ' ',
  },
  git = {
    added = ' ',
    modified = ' ',
    removed = ' ',
  },
  kinds = {
    Array = ' ',
    Boolean = '󰨙 ',
    Class = ' ',
    Codeium = '󰘦 ',
    Color = ' ',
    Control = ' ',
    Collapsed = ' ',
    Constant = '󰏿 ',
    Constructor = ' ',
    Copilot = ' ',
    Emoji = '󰞅 ',
    Enum = ' ',
    EnumMember = ' ',
    Event = ' ',
    Field = ' ',
    File = ' ',
    Folder = ' ',
    Function = '󰊕 ',
    Interface = ' ',
    Key = ' ',
    Keyword = ' ',
    Laravel = ' ',
    LazyDev = '󰒲 ',
    Method = '󰊕 ',
    Module = ' ',
    Namespace = '󰦮 ',
    Null = ' ',
    Number = '󰎠 ',
    Object = ' ',
    Operator = ' ',
    Package = ' ',
    Property = ' ',
    Reference = ' ',
    Snippet = ' ',
    String = ' ',
    Struct = '󰆼 ',
    Text = ' ',
    TypeParameter = ' ',
    Unit = ' ',
    Value = ' ',
    Variable = '󰀫 ',
  },
  statusline = {
    debugger = ' ',
    ai_sidekick = '󰚩 ',
    copilot = ' ',
    copilot_stopped = ' ',
    copilot_warning = ' ',
  },
  package = {
    installing = '󰏗 ',
    updating = '󰚰 ',
    deleting = '󰆴 ',
    fetching = '󰄉 ',
    success = '󰄬 ',
    error = '󰅙 ',
  },
  ai_sidekick = {
    attached = ' ',
    started = ' ',
    installed = ' ',
    missing = ' ',
    external_attached = '󰖩 ',
    external_started = '󰖪 ',
    terminal_attached = ' ',
    terminal_started = ' ',
  },
  file = {
    modified = ' ',
    readonly = ' ',
  },
}

return M
