# yaml-language-server: $schema=https://json.schemastore.org/lazydocker.json
gui:
  showFileIcons: true
  nerdFontsVersion: "3"
  # Use the mocha catppuccin theme
  theme:
    activeBorderColor:
      - "#89b4fa"
      - bold
    inactiveBorderColor:
      - "#a6adc8"
    optionsTextColor:
      - "#89b4fa"
    selectedLineBgColor:
      - "#313244"
